In [1]:
from MyRegressor import MyRegressor
from utils import *
import numpy as np

# creating/importing data
data_gauss = prepare_data_gaussian()

# creating regressor
reg = MyRegressor(alpha=0)

In [2]:
# code testing data
X_test = data_gauss["trainX"]
Y_test = data_gauss["trainY"]

In [6]:

selectX, selectY = reg.select_sample(X_test, Y_test, 50)
print(selectX.shape)
print(selectY.shape)

initialized
assigning
updating
going in
exited
terminal
(50, 500)
(50,)


In [10]:
print(X_test)
print(Y_test)

[[-0.04388943 -0.41839935  0.11095485]
 [-0.56192504  0.46752992  1.26951023]
 [ 0.84674886  1.02745109 -0.06907263]]
[ 55.19873934  -0.99637689 -15.12030081]


In [6]:
N, M = data_gauss["trainX"].shape
theta = res.x[-(M+1): -1]
bias = res.x[-1]
est = np.matmul(data_gauss["trainX"], theta) + bias*np.ones((600,))
print(bias)
print(est)

0.5757670893166374
[ 3.68480128e+01 -1.74932758e+01 -2.56242813e+01 -1.33789258e+01
 -2.29465201e+01  4.51998736e+00 -6.10546366e+00 -2.10842045e+01
 -2.10648412e+01  1.17076034e+01 -2.05246168e+01 -3.61752072e+00
  1.40696617e+01  3.58271679e+00 -3.24861489e+01 -2.08136075e+01
  6.98019400e+00  1.47346513e+01  2.35067336e+01  1.01030802e+01
  1.39801893e+00  4.39706912e+01 -4.42284377e+00 -2.23177699e+01
  3.31500006e+01 -7.32004354e+01  3.81499904e+01 -1.16385131e+01
 -1.40084334e+01 -1.04418109e+01  1.39682745e+01 -2.44266984e+00
  3.64863682e+01 -2.85756720e+01 -5.39495599e+00  1.60748305e+01
  2.78727037e+01  2.16714101e+01 -1.92501956e+01  8.32928148e+00
  1.73970442e+01 -1.18732486e+01  1.44186453e+01 -1.85617428e+01
  1.27794975e+01  4.41840349e+01  3.44042194e+00  5.42016850e-01
  2.53679118e+01  1.99053183e-01  1.02905325e+01 -6.92315485e+00
  1.25483436e+01  1.08869870e+01 -3.06022818e+01  2.67344522e+01
 -8.69032539e+00  5.08058933e+01  4.14871809e+01 -3.33647723e+01
  1.35

In [7]:
print(data_gauss["trainY"])

[ 3.68480128e+01 -1.73762948e+01 -2.61187216e+01 -1.33789258e+01
 -2.25602111e+01  4.51998736e+00 -6.01648382e+00 -2.10321833e+01
 -2.10648412e+01  1.17189084e+01 -2.05246168e+01 -3.61752072e+00
  1.37113462e+01  3.34548839e+00 -3.10378731e+01 -2.11056209e+01
  6.69118570e+00  1.47243638e+01  2.34940082e+01  1.01030802e+01
  1.83699474e+00  4.39706912e+01 -4.42284377e+00 -2.23177699e+01
  3.31500006e+01 -7.25647402e+01  3.81499904e+01 -1.16385131e+01
 -1.42237635e+01 -1.04418109e+01  1.39682745e+01 -3.13584667e+00
  3.64863682e+01 -2.85756720e+01 -5.39495599e+00  1.57859142e+01
  2.78727037e+01  2.16714101e+01 -1.85779513e+01  9.68183991e+00
  1.73970442e+01 -1.18732486e+01  1.44109367e+01 -1.89904567e+01
  1.27794975e+01  4.41840349e+01  3.63585719e+00  7.81355366e-01
  2.53679118e+01  1.99053183e-01  9.96573725e+00 -6.98697144e+00
  1.25483436e+01  1.08869870e+01 -3.06022818e+01  2.67344522e+01
 -8.69032539e+00  5.08058933e+01  4.14871809e+01 -3.33647723e+01
  1.42625586e+01 -2.06900

In [8]:
print(est - data_gauss["trainY"])

[-7.74491582e-13 -1.16980972e-01  4.94440278e-01 -7.72715225e-13
 -3.86308985e-01  1.23900890e-12 -8.89798381e-02 -5.20211828e-02
 -8.17124146e-14 -1.13050482e-02  1.06226139e-12 -3.46389584e-14
  3.58315505e-01  2.37228401e-01 -1.44827576e+00  2.92013437e-01
  2.89008300e-01  1.02875903e-02  1.27253497e-02 -2.38031816e-13
 -4.38975811e-01  1.09423581e-12  3.92574862e-13 -9.94759830e-14
 -1.91846539e-13 -6.35695189e-01  2.62900812e-13  1.70530257e-13
  2.15330148e-01  3.46389584e-13  3.01980663e-14  6.93176822e-01
  1.58451030e-12  5.64881475e-13 -1.12088117e-12  2.88916328e-01
 -3.12638804e-13  8.17124146e-14 -6.72244310e-01 -1.35255843e+00
  1.78701498e-12 -5.13367127e-13  7.70856887e-03  4.28713848e-01
 -9.23705556e-13  7.46069873e-13 -1.95435249e-01 -2.39338516e-01
 -3.62376795e-13 -5.12423437e-13  3.24795251e-01  6.38165820e-02
  6.03961325e-14  1.11732845e-12  1.55608859e-12  1.04094511e-12
 -5.47117907e-13  3.83693077e-13 -3.55271368e-13 -2.13162821e-13
 -6.88493366e-01 -4.49188